# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 423)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 20, 160, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbsinema = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbsinema.setTristate(False)
        self.cbsinema.setObjectName("cbsinema")
        self.verticalLayout.addWidget(self.cbsinema)
        self.cbkitapokumak = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbkitapokumak.setObjectName("cbkitapokumak")
        self.verticalLayout.addWidget(self.cbkitapokumak)
        self.cbspor = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbspor.setObjectName("cbspor")
        self.verticalLayout.addWidget(self.cbspor)
        self.btnsecilenlerial = QtWidgets.QPushButton(self.centralwidget)
        self.btnsecilenlerial.setGeometry(QtCore.QRect(130, 240, 93, 28))
        self.btnsecilenlerial.setObjectName("btnsecilenlerial")
        self.lblresult = QtWidgets.QLabel(self.centralwidget)
        self.lblresult.setGeometry(QtCore.QRect(280, 20, 181, 161))
        self.lblresult.setText("")
        self.lblresult.setObjectName("lblresult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cbsinema.setText(_translate("MainWindow", "sinema"))
        self.cbkitapokumak.setText(_translate("MainWindow", "kitap okumak"))
        self.cbspor.setText(_translate("MainWindow", "spor"))
        self.btnsecilenlerial.setText(_translate("MainWindow", "seçilenleri al"))
