# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbsehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbsehirler.setGeometry(QtCore.QRect(90, 70, 111, 31))
        self.cbsehirler.setObjectName("cbsehirler")
        self.cbsehirler.addItem("")
        self.cbsehirler.addItem("")
        self.cbsehirler.addItem("")
        self.btnitem = QtWidgets.QPushButton(self.centralwidget)
        self.btnitem.setGeometry(QtCore.QRect(90, 110, 93, 28))
        self.btnitem.setObjectName("btnitem")
        self.btnload = QtWidgets.QPushButton(self.centralwidget)
        self.btnload.setGeometry(QtCore.QRect(90, 150, 93, 28))
        self.btnload.setObjectName("btnload")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 230, 131, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cbsehirler.setItemText(0, _translate("MainWindow", "Ankara"))
        self.cbsehirler.setItemText(1, _translate("MainWindow", "İstanbul"))
        self.cbsehirler.setItemText(2, _translate("MainWindow", "Kocaeli"))
        self.btnitem.setText(_translate("MainWindow", "get item"))
        self.btnload.setText(_translate("MainWindow", "load items"))
        self.pushButton.setText(_translate("MainWindow", "temizle"))
