import numpy as np # verileri analiz etmek için biçilmişkaftan...

# 10 15 30 45 60 değerlerine sahip bir bir numpy dizisi...
result = np.array([10,15,30,45,60])
# 5 15 arasındaki sayılar ile bir numpy dizisi...
result1 = np.arange(5,15)
# 5 ile 100 arasında 5er artan değerli bir dizi olusturun...
result2 = np.arange(5,100,5)
# 10 elemanlı sıfırlardan olusan bir dizi...
result3 = np.zeros(10)
# 10 elemanlı birlerden olusan bir dizi...
result4 = np.ones(10) 
# 0 100 arasın eşit aralıklı 5 sayı üretim..
result5 = np.linspace(0,100,5)
# 10 30 arasında rastgele 5 tane tam sayı üretin...
result6 = np.random.randint(10,30,5)
# -1 ile 1 arasında 10 adet sayı üretin...
result7 = np.random.randn(-1,1,10)
# 3x5 lik bir matris elemanları ise 10 50 arasında rastgele sayılardan olsun...
result8 = np.random.randint(10,50,15).reshape(3,5)
# üretilen matrisin satir ve sutunlarının toplamları...
result9 = result8.sum(axis=1)
result10 = result8.sum(axis=0)
# üretilen matrisin en büyük en küçük ve ortalama degeri nedir...
maxdeger = result8.max()
mindeger = result8.min()
ortalama = result8.mean()
# üretilen matrisin en büyük ve en kucuk degerinin indexi nedir..
minindex = result8.argmin()
maxindex = result8.argmax()
# 10 ile 20 arasında sayıları içeren dizini ilk üç elemanı
array = np.arange(10,20)
kesim = array[:3]
# üretilen elemanları tersten array yapın...
tersarray = array[::-1]
# üretilen matrisin ilk satırını seçiniz...
matris1 = np.random.randint(10,50,15).reshape(3,5)
satir = matris1[0]
# üretilen matrisin ikinci satır 3. sutundaki elemanlarını alınız...
TT = matris1[1,2]
#  üretilen matrisin tüm satırlarındaki ilk elemanı seçiniz...
YY = matris1[:,0] 
# üretilen matrisin tüm elemanlarının karesini alın...
UU = matris1 ** 2 # tüm elemanları dönecek ve hepsinin karesini alacak...

# üretilen matrisin elemanlarının hangisi pozitif hangisi çift sayıdır...
newarray1 = np.random.rand(-50,50,15).reshape(3,5)
booller = newarray1 >= 0
ciftler = newarray1[newarray1 % 2 == 0]
ciftler = ciftler[ciftler > 0]
