import numpy as np

numbers = np.array([0,5,10,15,20,25,50,75])

result = numbers[5] #5. indexteki elemanı getirir...
result2 = numbers[-1] # en sondaki elemanı getirir...
result3 = numbers[0:3] # 0 1 2. indexlerdeli elemanları bir listeye koyar ve getirir... liste indexleme gibi...
result4 = numbers[3:] # 3. index dahil sona kadar olan elemanları bir listeye atar...
result5 = numbers[::-1] # arrayi ters çevirebiliriz...
result6 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # bir matris oluşur burada...

print(result6[1,1]) # ikinci arrayin ikinci değerini alırız... matrislerde işlem böyle olur...
print(result6[:,2]) # tüm satıların. 2. kolonundaki değerleri getirir...
print(result6[:,0:2]) # her satırın 0 ile 2. index arasını getirir. yani 0 ve 1. indexlerdeli elemanlarını getirir...
print(result6[-1,:]) # son satirdaki tüm değerleri alırız böylece...
 
